# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"print_test": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://herculanodavi.github.io/apre_nbdev/"

git_url = "https://github.com/herculanodavi/apre_nbdev/tree/master/"

def custom_doc_links(name): return None
